version: '3'

services:
  app:
    image: python:3.11-slim
    container_name: openai-image-playground
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "7860:7860"
    command: >
      bash -c "pip install -r requirements.txt && 
              python app.py --server_name=0.0.0.0"
    restart: unless-stopped
    environment:
      - API_KEY=${API_KEY}
      - API_ENDPOINT=${API_ENDPOINT}